-- match_change_logs : à exécuter APRÈS avoir créé les comptes staff
-- (scripts/create-staff-user.mjs) avec les MÊMES usernames que l'app PHP :
-- admin, arbitre1, arbitre2

insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 24, sr.user_id, 'admin', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-04-26 08:03:54' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 23, sr.user_id, 'admin', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-04-26 08:04:25' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 21, sr.user_id, 'admin', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-04-26 08:06:21' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 21, sr.user_id, 'admin', 'update_match_state', 'En cours', 'Termine', 110, 110, 200, 200, true, true, '2026-04-26 08:36:29' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 24, sr.user_id, 'admin', 'update_match_state', 'En cours', 'Termine', 50, 50, 90, 90, true, true, '2026-04-26 08:38:59' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 23, sr.user_id, 'admin', 'update_match_state', 'En cours', 'Termine', 70, 70, 210, 210, true, true, '2026-04-26 08:48:58' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 26, sr.user_id, 'admin', 'update_match_state', 'En cours', 'Termine', 230, 230, 160, 160, true, true, '2026-04-26 10:33:34' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 29, sr.user_id, 'arbitre2', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-05-31 07:57:20' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 28, sr.user_id, 'arbitre2', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-05-31 08:07:10' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 30, sr.user_id, 'arbitre1', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-05-31 08:07:12' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 31, sr.user_id, 'arbitre1', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-05-31 08:09:04' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 29, sr.user_id, 'arbitre2', 'update_match_state', 'En cours', 'Termine', 200, 200, 190, 190, true, true, '2026-05-31 08:28:13' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 30, sr.user_id, 'arbitre1', 'update_match_state', 'En cours', 'Termine', 280, 280, 250, 250, true, true, '2026-05-31 08:30:47' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 28, sr.user_id, 'arbitre2', 'update_match_state', 'En cours', 'Termine', 190, 190, 190, 190, true, true, '2026-05-31 08:40:00' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 31, sr.user_id, 'admin', 'update_match_state', 'En cours', 'Termine', 160, 160, 210, 210, true, true, '2026-05-31 08:53:55' from staff_roles sr where sr.username = 'admin';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 32, sr.user_id, 'arbitre1', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-06-28 08:11:07' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 34, sr.user_id, 'arbitre1', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-06-28 08:15:22' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 33, sr.user_id, 'arbitre2', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-06-28 08:17:10' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 35, sr.user_id, 'arbitre2', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-06-28 08:18:58' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 34, sr.user_id, 'arbitre1', 'update_match_state', 'En cours', 'Termine', 160, 160, 100, 100, true, true, '2026-06-28 08:42:44' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 32, sr.user_id, 'arbitre1', 'update_match_state', 'En cours', 'Termine', 130, 130, 100, 100, true, true, '2026-06-28 08:45:31' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 33, sr.user_id, 'arbitre2', 'update_match_state', 'En cours', 'Termine', 60, 60, 140, 140, true, true, '2026-06-28 08:47:09' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 35, sr.user_id, 'arbitre2', 'update_match_state', 'En cours', 'Termine', 80, 80, 140, 140, true, true, '2026-06-28 08:51:20' from staff_roles sr where sr.username = 'arbitre2';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 37, sr.user_id, 'arbitre1', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-07-26 08:00:33' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 37, sr.user_id, 'arbitre1', 'update_match_state', 'En cours', 'Termine', 160, 160, 60, 60, true, true, '2026-07-26 08:23:51' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 36, sr.user_id, 'arbitre1', 'update_match_state', 'Programme', 'En cours', 0, 0, 0, 0, true, true, '2026-07-26 08:27:53' from staff_roles sr where sr.username = 'arbitre1';
insert into match_change_logs (match_id, staff_user_id, staff_username, action, old_status, new_status, old_score_team1, new_score_team1, old_score_team2, new_score_team2, old_published, new_published, created_at) select 36, sr.user_id, 'arbitre1', 'update_match_state', 'En cours', 'Termine', 130, 130, 110, 110, true, true, '2026-07-26 09:37:44' from staff_roles sr where sr.username = 'arbitre1';
